Menu responsive
luis-prates/ft_transcendence pull request #50
Opened 2023-08-21 15:52 UTC by RubenTeles

transform menus canvas in vue

2023-08-21 23:00 UTC, luis-prates requested changes
Muita coisa aqui feita! So uns reparos mas fora isso parece bem. Tenho de testar. Obrigado!

2023-08-22 12:25 UTC, RubenTeles commented on frontend/src/components/menus/MyProfileComponent.vue
> +const defaultAvatar = "../../src/assets/chat/avatar.png";
done

2023-08-22 12:26 UTC, RubenTeles commented on frontend/src/components/menus/ProfileComponent.vue
> +
vai ser a implementacao do eduardo para enviar mensagem privada

2023-08-22 12:28 UTC, RubenTeles commented on frontend/src/components/menus/ShopCommponent.vue
> +    background-image: url('src/assets/images/lobby/115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg');
esse é a imagem de avatares, mas ya ja mudei para "avatares", no css nao consegui meter sem ser por path

2023-08-22 12:29 UTC, RubenTeles commented on frontend/src/components/menus/SpeechBubbleComponent.vue
> +    background-image: url('src/assets/images/lobby/115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg');
? nao entendi, acho que esta a ser bastante claro

2023-08-22 14:50 UTC, Eduuxx94 commented on frontend/src/components/menus/SpeechBubbleComponent.vue
> +    background-image: url('src/assets/images/lobby/115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg');
ele está a falar do nome do ficheiro: 115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg

2023-08-22 15:26 UTC, luis-prates commented on frontend/src/components/menus/SpeechBubbleComponent.vue
> +    background-image: url('src/assets/images/lobby/115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg');
Sim, exato. Estava a falar do nome do ficheiro em si

2023-08-22 15:27 UTC, luis-prates commented on frontend/src/components/menus/ShopCommponent.vue
> +    background-image: url('src/assets/images/lobby/115990-9289fbf87e73f1b4ed03565ed61ae28e.jpg');
Aqui igual. O nome do ficheiro em si

2023-08-23 01:17 UTC, luis-prates requested changes

2023-08-23 01:17 UTC, luis-prates commented on frontend/src/components/menus/TwoFactorComponent.vue
> +});
Isto não esta correto. Esta a gerar um novo QRCode quando se quer ativar (como é suposto) e esta a gerar outro codigo novo quando se quer desativar (não é suposto). O codigo para desativar tem de ser baseado no QRCode usado na ativação. Isto antes estava bem, se não me engano, mas como tens isso no onMounted, sempre que abre a janela faz a chamada de API para o backend para pedir um novo codigo. A consequencia é que se carregares no botão para desativar e depois cancelares, quando tentares fazer log in de novo, o QRCode lido na ativação não vai ser válido

2023-08-23 21:11 UTC, luis-prates requested changes

2023-08-23 21:11 UTC, luis-prates commented on frontend/src/game/lobby/objects/Camera.ts
> +    console.log("x: ", this.x, "y: ", this.y, "width: ", this.width, "height: ", this.height, )
Apaga este log sff, isto esta a ser posto no output prai 100x por segundo. Afeta a performance

2023-08-25 13:52 UTC, luis-prates approved these changes
Obrigado pelos fixes!

2023-08-25 13:52 UTC, merged