Chat implementation done
luis-prates/ft_transcendence pull request #52
Opened 2023-08-28 12:48 UTC by Eduuxx94

Chat está concluído, só falta agora o Rubén chamar a minha função para fazer DM.
Exemplo:
    Menu.chatListRef({id: user.id} as ChatUser);

2023-08-28 13:09 UTC, Hevhove commented
Why is this PR already closed?

2023-08-28 22:13 UTC, luis-prates requested changes
A funcionalidade do mute parece estar okay! As únicas coisas a melhorar neste PR são o menu do mute que nao esta a mostrar as opçoes todas (posicionamento da caixa) e, se possivel, desativar a caixa de texto da pessoa muted. Ficaria bem tambem um contador de tempo ate o mute acabar, mas isso deixo ao teu criterio

2023-08-29 08:34 UTC, Eduuxx94 commented
Não dá para pôr um timer como pediste, pois o servidor não me manda qualquer informação do tempo em que um user fica muted, posso sim desativar a caixa de texto para que o user fique a saber que está muted ou desabilitado de escrever no channel. Em relação ao posicionamento da caixa de menu ainda não entendi o que pode ser, às vezes está a funcionar corretamente outras vezes não... Tenho que explorar isso a ver se consigo fazer o fix.

2023-08-29 08:50 UTC, luis-prates commented
> Não dá para pôr um timer como pediste, pois o servidor não me manda qualquer informação do tempo em que um user fica muted, posso sim desativar a caixa de texto para que o user fique a saber que está muted ou desabilitado de escrever no channel. Em relação ao posicionamento da caixa de menu ainda não entendi o que pode ser, às vezes está a funcionar corretamente outras vezes não... Tenho que explorar isso a ver se consigo fazer o fix.

o tempo deve ser algo facil de mandar de volta, o Hendrik deve conseguir tratar disso facilmente. @Hevhove can you send the mute time on the mute event to the user being muted?

2023-08-29 09:11 UTC, Hevhove commented
> > Não dá para pôr um timer como pediste, pois o servidor não me manda qualquer informação do tempo em que um user fica muted, posso sim desativar a caixa de texto para que o user fique a saber que está muted ou desabilitado de escrever no channel. Em relação ao posicionamento da caixa de menu ainda não entendi o que pode ser, às vezes está a funcionar corretamente outras vezes não... Tenho que explorar isso a ver se consigo fazer o fix.
> 
> o tempo deve ser algo facil de mandar de volta, o Hendrik deve conseguir tratar disso facilmente. @Hevhove can you send the mute time on the mute event to the user being muted?

Yes that is a simple fix, I can add it!

2023-08-29 09:20 UTC, Hevhove commented
What is good here:

- Muting seems to be working fine, and the duration is working
- The message button inside of the user profile is working now, that's also good.
- Inclusion of Protected as an option - great!
- Protected 'lock' is now showing after editing the channel to protected
- When a channel was changed to PROTECTED, now it is asking for the password. Good!
- ONLINE/OFFLINE status looks correct now.

This can be for another PR, but one thing we are still missing now is the [profile-picture-changed] event which needs to come from user profile.

As discussed above, I will do the event with muteDuration now to the user.

2023-08-29 12:32 UTC, Eduuxx94 commented
> What is good here:
> 
> * Muting seems to be working fine, and the duration is working
> * The message button inside of the user profile is working now, that's also good.
> * Inclusion of Protected as an option - great!
> * Protected 'lock' is now showing after editing the channel to protected
> * When a channel was changed to PROTECTED, now it is asking for the password. Good!
> * ONLINE/OFFLINE status looks correct now.
> 
> This can be for another PR, but one thing we are still missing now is the [profile-picture-changed] event which needs to come from user profile.
> 
> As discussed above, I will do the event with muteDuration now to the user.

Since that change comes from userStore ruben sayed that will fix that, i still need to do the block implementatio, css fix submenu and text box disabled.

2023-08-30 15:49 UTC, Eduuxx94 commented
Sim eu falei com o @RubenTeles ainda esta semana sobre isso.

2023-09-03 17:45 UTC, Eduuxx94 commented
Its done, please can someone review?

2023-09-04 06:56 UTC, luis-prates commented
> Its done, please can someone review?

Yes, I've reviewed it, but I'll wait for @Hevhove to arrive to test with him and for him to take a look at the functionality

2023-09-04 15:08 UTC, Hevhove approved these changes
Thanks for the work. Went through this with @luis-prates and implemented a fix for the blocking behaviour.

2023-09-04 15:13 UTC, luis-prates approved these changes
Seems to be fine, thank you!

2023-09-04 15:13 UTC, merged